#!/usr/bin/env node
/**
 * Minimal post-processing of codegen output into verb-nurbs.d.ts
 *
 * This script only does things codegen structurally cannot:
 *   1. Flatten nested class paths (codegen mapper bug with @:expose prefix matching)
 *   2. Clean up remaining verb.* prefixes on references
 *   3. Wrap in declare module 'verb-nurbs' with typedef aliases and default export
 */

const fs = require('fs');
const path = require('path');

const INPUT = path.join(__dirname, '..', 'build', 'js', 'verb-nurbs.generated.d.ts');
const OUTPUT = path.join(__dirname, '..', 'build', 'js', 'verb-nurbs.d.ts');

let content = fs.readFileSync(INPUT, 'utf-8');

// 1. Flatten nested class paths — codegen's mapper can't handle these because
//    the @:expose prefix match on the parent class overrides the exact match.
//    See: https://github.com/yar3333/haxe-codegen Tools.mapType lines 184-187
const flattenMap = {
  'eval.Divide.CurveLengthSample': 'eval.CurveLengthSample',
  'eval.Tess.AdaptiveRefinementOptions': 'eval.AdaptiveRefinementOptions',
  'eval.Tess.AdaptiveRefinementNode': 'eval.AdaptiveRefinementNode',
  'eval.Analyze.KnotMultiplicity': 'eval.KnotMultiplicity',
  'eval.Intersect.IBoundingBoxTree': 'eval.IBoundingBoxTree',
  'core.KdTree.KdPoint': 'core.KdPoint',
  'core.KdTree.KdNode': 'core.KdNode',
  'core.Minimizer.MinimizationResult': 'core.MinimizationResult',
};

for (const [from, to] of Object.entries(flattenMap)) {
  content = content.replaceAll(from, to);
}

// 2. Clean up remaining verb.* prefixes that the mapper couldn't resolve
content = content.replaceAll('verb.core.Intersections.SurfacePoint', 'eval.SurfacePoint');
content = content.replaceAll('verb.core.Serialization.ISerializable', 'geom.ISerializable');
content = content.replaceAll('promhx.base.AsyncBase', 'promhx.AsyncBase');

// 3. Remove wrongly-namespaced blocks generated by codegen's include()
content = content.replace(/^export namespace verb\.geom\n\{[\s\S]*?\n\}\n*/gm, '');
content = content.replace(/^export namespace core\.Deserializer\n\{[\s\S]*?\n\}\n*/gm, '');
content = content.replace(/^export namespace core\.Interval\n\{[\s\S]*?\n\}\n*/gm, '');
content = content.replace(/^export namespace core\.Intersections\n\{[\s\S]*?\n\}\n*/gm, '');

// 4. Inject stubs for types that codegen structurally cannot generate:
//    - AsyncBase: promhx internal base class, not exposed
//    - IBoundingBoxTree: Haxe interface in a module codegen can't include without naming conflicts
content = content.replace(
  /^(export namespace promhx\n\{)/m,
  '$1\n\texport class AsyncBase<T> {}\n'
);
content = content.replace(
  /^(export namespace eval\n\{)/m,
  `$1
\texport interface IBoundingBoxTree<T> {
\t\tboundingBox(): core.BoundingBox;
\t\tsplit(): [IBoundingBoxTree<T>, IBoundingBoxTree<T>];
\t\tyield(): T;
\t\tindivisible(tolerance: number): boolean;
\t\tempty(): boolean;
\t}
`
);

// 5. Wrap in module declaration
const indented = content.split('\n').map(l => l ? '\t' + l : l).join('\n');

const TYPEDEFS = `\ttype Point = number[];
\ttype Vector = number[];
\ttype Matrix = number[][];
\ttype KnotArray = number[];
\ttype Tri = number[];
\ttype UV = number[];`;

const output = `/*
 * TypeScript definitions for verb-nurbs
 * Generated by: haxe buildjs-codegen.hxml && node scripts/fix-dts.js
 */
declare module 'verb-nurbs' {
${TYPEDEFS}

${indented}
\tinterface Verb {
\t\tEPSILON: number;
\t\tTOLERANCE: number;
\t\tVERSION: string;
\t\tpromhx: typeof promhx;
\t\tcore: typeof core;
\t\teval: typeof eval;
\t\texe: typeof exe;
\t\tgeom: typeof geom;
\t}

\tconst verb: Verb;
\texport default verb;
}
`;

fs.writeFileSync(OUTPUT, output);
console.log(`${OUTPUT}: ${output.split('\n').length} lines`);
